const transliterate = (word) => {
  let answer = "";
  let alphabet = {};

  alphabet["Ё"] = "YO";
  alphabet["Й"] = "I";
  alphabet["Ц"] = "TS";
  alphabet["У"] = "U";
  alphabet["К"] = "K";
  alphabet["Е"] = "E";
  alphabet["Н"] = "N";
  alphabet["Г"] = "G";
  alphabet["Ш"] = "SH";
  alphabet["Щ"] = "SCH";
  alphabet["З"] = "Z";
  alphabet["Х"] = "H";
  alphabet["Ъ"] = "'";
  alphabet["ё"] = "yo";
  alphabet["й"] = "i";
  alphabet["ц"] = "ts";
  alphabet["у"] = "u";
  alphabet["к"] = "k";
  alphabet["е"] = "e";
  alphabet["н"] = "n";
  alphabet["г"] = "g";
  alphabet["ш"] = "sh";
  alphabet["щ"] = "sch";
  alphabet["з"] = "z";
  alphabet["х"] = "h";
  alphabet["ъ"] = "'";
  alphabet["Ф"] = "F";
  alphabet["Ы"] = "I";
  alphabet["В"] = "V";
  alphabet["А"] = "a";
  alphabet["П"] = "P";
  alphabet["Р"] = "R";
  alphabet["О"] = "O";
  alphabet["Л"] = "L";
  alphabet["Д"] = "D";
  alphabet["Ж"] = "ZH";
  alphabet["Э"] = "E";
  alphabet["ф"] = "f";
  alphabet["ы"] = "i";
  alphabet["в"] = "v";
  alphabet["а"] = "a";
  alphabet["п"] = "p";
  alphabet["р"] = "r";
  alphabet["о"] = "o";
  alphabet["л"] = "l";
  alphabet["д"] = "d";
  alphabet["ж"] = "zh";
  alphabet["э"] = "e";
  alphabet["Я"] = "Ya";
  alphabet["Ч"] = "CH";
  alphabet["С"] = "S";
  alphabet["М"] = "M";
  alphabet["И"] = "I";
  alphabet["Т"] = "T";
  alphabet["Ь"] = "'";
  alphabet["Б"] = "B";
  alphabet["Ю"] = "YU";
  alphabet["я"] = "ya";
  alphabet["ч"] = "ch";
  alphabet["с"] = "s";
  alphabet["м"] = "m";
  alphabet["и"] = "i";
  alphabet["т"] = "t";
  alphabet["ь"] = "'";
  alphabet["б"] = "b";
  alphabet["ю"] = "yu";

  for (let i = 0; i < word.length; ++i) {
    answer += alphabet[word[i]] === undefined ? word[i] : alphabet[word[i]];
  }
  return [word, answer];
};
